#!/usr/bin/env python3
"""Add a Hindi vocab card to Anki from just a Devanagari word: looks up a pool
of candidate images via SerpApi (Google Images), uses Claude (vision) to pick
the 4-5 most relevant/representative ones, fetches an audio pronunciation via
Forvo, and generates an English-phonetic pronunciation guide via Claude.
Inserts a note into the "Hindi Vocab" deck (model "Hindi gDocs").

Usage:
  python3 add_card.py --hindi "किताब" --english "book" --gender "F"

English/Gender are optional. Pronunciation is generated by Claude unless
--pronunciation is passed explicitly. Requires the anthropic package
(installed in .venv) - run via .venv/bin/python3 add_card.py ...
"""
import argparse
import base64
import json
import os
import sys
import urllib.parse
import urllib.request

import anthropic

ANKI_URL = "http://127.0.0.1:8765"
DECK = "Claude Cards"
MODEL = "Hindi gDocs"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
TMP_DIR = "/tmp/hindi_anki_images"
IMAGE_CANDIDATE_POOL = 15
PROMPTS_DIR = os.path.join(SCRIPT_DIR, "prompts")
PRONUNCIATION_PROMPT_PATH = os.path.join(PROMPTS_DIR, "pheonetic_pronounciation_prompt.md")
IMAGE_SEARCH_PROMPT_PATH = os.path.join(PROMPTS_DIR, "google_image_search_prompt.md")
EXAMPLE_SENTENCE_PROMPT_PATH = os.path.join(PROMPTS_DIR, "example_sentence_prompt.md")


def load_env(path):
    env = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    return env


def anki_request(action, **params):
    payload = json.dumps({"action": action, "version": 6, "params": params}).encode()
    req = urllib.request.Request(ANKI_URL, data=payload)
    with urllib.request.urlopen(req) as resp:
        result = json.load(resp)
    if result.get("error"):
        raise RuntimeError(f"AnkiConnect error on {action}: {result['error']}")
    return result["result"]


def search_images(search_query, api_key, num=3):
    query = urllib.parse.urlencode(
        {
            "engine": "google_images",
            "q": search_query,
            "api_key": api_key,
            "safe": "active",
        }
    )
    url = f"https://serpapi.com/search.json?{query}"
    try:
        with urllib.request.urlopen(url) as resp:
            data = json.load(resp)
    except urllib.error.HTTPError as e:
        body = e.read().decode(errors="replace")
        raise RuntimeError(f"SerpApi HTTP {e.code}: {body}") from None
    if "error" in data:
        raise RuntimeError(f"SerpApi error: {data['error']}")
    results = data.get("images_results", [])
    return [item["original"] for item in results[:num] if "original" in item]


def load_image_search_prompt_template():
    with open(IMAGE_SEARCH_PROMPT_PATH, encoding="utf-8") as f:
        return f.read()


def generate_image_search_query(word, english, api_key):
    template = load_image_search_prompt_template()
    prompt = template.replace("{{WORD}}", word).replace("{{ENGLISH}}", english or "(not provided)")
    client = anthropic.Anthropic(api_key=api_key)
    response = client.messages.create(
        model="claude-opus-5",
        max_tokens=150,
        output_config={"effort": "low"},
        messages=[{"role": "user", "content": prompt}],
    )
    text = next((b.text for b in response.content if b.type == "text"), "")
    return text.strip() or word


def download_file(url, dest):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=10) as resp:
        data = resp.read()
    with open(dest, "wb") as f:
        f.write(data)


MAX_IMAGE_BYTES = 5 * 1024 * 1024


def guess_media_type(path):
    with open(path, "rb") as f:
        header = f.read(12)
    if header.startswith(b"\xff\xd8"):
        return "image/jpeg"
    if header.startswith(b"\x89PNG"):
        return "image/png"
    if header[:6] in (b"GIF87a", b"GIF89a"):
        return "image/gif"
    if header[:4] == b"RIFF" and header[8:12] == b"WEBP":
        return "image/webp"
    return None


def select_best_images(word, english, paths, api_key, keep=5):
    usable = [p for p in paths if guess_media_type(p) and os.path.getsize(p) <= MAX_IMAGE_BYTES]
    if len(usable) <= keep:
        return usable

    client = anthropic.Anthropic(api_key=api_key)
    blocks = []
    for i, path in enumerate(usable):
        with open(path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode()
        blocks.append({"type": "text", "text": f"Image {i}:"})
        blocks.append(
            {
                "type": "image",
                "source": {"type": "base64", "media_type": guess_media_type(path), "data": b64},
            }
        )
    meaning = f' (meaning: "{english}")' if english else ""
    blocks.append(
        {
            "type": "text",
            "text": (
                f'These are candidate images from a Google Images search meant to illustrate the '
                f'Hindi word "{word}"{meaning}, for a vocabulary flashcard. The goal is for a '
                f"learner to look at the image and intuitively grasp what the word means, purely "
                f"from the visual — so strongly prefer real, clear photographs of the actual "
                f"concept over anything else. Reject: text overlays, captions, watermarks, logos, "
                f"dictionary/definition graphics, icons or clipart, screenshots, memes, unrelated "
                f"subjects, and low-quality/blurry photos. Pick the {keep} images that most "
                f"clearly and unambiguously depict this word's meaning. Reply with ONLY a "
                f'comma-separated list of the chosen image numbers, most representative first '
                f'(e.g. "3,0,7,1,5"), nothing else.'
            ),
        }
    )
    try:
        response = client.messages.create(
            model="claude-opus-5",
            max_tokens=200,
            output_config={"effort": "low"},
            messages=[{"role": "user", "content": blocks}],
        )
    except anthropic.APIError as e:
        print(f"  (image selection failed, falling back to first {keep} candidates: {e})")
        return usable[:keep]
    text = next((b.text for b in response.content if b.type == "text"), "")

    indices = []
    for tok in text.replace(" ", "").split(","):
        if tok.isdigit() and int(tok) < len(usable):
            indices.append(int(tok))

    if not indices:
        return usable[:keep]

    seen = set()
    ordered = []
    for idx in indices:
        if idx not in seen:
            seen.add(idx)
            ordered.append(usable[idx])
        if len(ordered) >= keep:
            break
    return ordered


def find_forvo_mp3_url(word, api_key):
    query = urllib.parse.quote(word)
    url = (
        f"https://apifree.forvo.com/key/{api_key}/format/json/"
        f"action/word-pronunciations/word/{query}/language/hi"
    )
    with urllib.request.urlopen(url, timeout=10) as resp:
        data = json.load(resp)
    items = data.get("items", [])
    if not items:
        return None
    best = max(items, key=lambda it: (it.get("num_positive_votes", 0), it.get("rate", 0)))
    return best["pathmp3"]


def load_pronunciation_prompt_template():
    with open(PRONUNCIATION_PROMPT_PATH, encoding="utf-8") as f:
        return f.read()


def get_pronunciation(word, api_key):
    template = load_pronunciation_prompt_template()
    prompt = template.replace("{{WORD}}", word)
    client = anthropic.Anthropic(api_key=api_key)
    response = client.messages.create(
        model="claude-opus-5",
        max_tokens=300,
        output_config={"effort": "low"},
        messages=[{"role": "user", "content": prompt}],
    )
    text = next((b.text for b in response.content if b.type == "text"), "")
    text = text.strip()

    for line in text.splitlines():
        line = line.strip()
        if line.lower().startswith("pronunciation:"):
            return line.split(":", 1)[1].strip()
    return text


def load_example_sentence_prompt_template():
    with open(EXAMPLE_SENTENCE_PROMPT_PATH, encoding="utf-8") as f:
        return f.read()


def generate_example_sentence(word, english, api_key):
    template = load_example_sentence_prompt_template()
    prompt = template.replace("{{WORD}}", word).replace("{{ENGLISH}}", english or "(not provided)")
    client = anthropic.Anthropic(api_key=api_key)
    response = client.messages.create(
        model="claude-opus-5",
        max_tokens=200,
        output_config={"effort": "low"},
        messages=[{"role": "user", "content": prompt}],
    )
    text = next((b.text for b in response.content if b.type == "text"), "")
    return text.strip()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--hindi", required=True)
    parser.add_argument("--english", default="")
    parser.add_argument("--gender", default="")
    parser.add_argument("--pronunciation", default="")
    parser.add_argument(
        "--images",
        type=int,
        default=7,
        help="max number of images to attach (best N chosen by Claude from a larger candidate pool)",
    )
    parser.add_argument("--deck", default=DECK, help="Anki deck to add the card to")
    args = parser.parse_args()

    env = load_env(os.path.join(SCRIPT_DIR, ".env"))
    serp_key = os.environ.get("SERPAPI_KEY") or env.get("SERPAPI_KEY")
    forvo_key = os.environ.get("FORVO_API_KEY") or env.get("FORVO_API_KEY")
    anthropic_key = os.environ.get("ANTHROPIC_API_KEY") or env.get("ANTHROPIC_API_KEY")
    if not serp_key:
        sys.exit("Missing SERPAPI_KEY (set as an env var or in .env)")
    if not forvo_key:
        sys.exit("Missing FORVO_API_KEY (set as an env var or in .env)")
    if not anthropic_key:
        sys.exit("Missing ANTHROPIC_API_KEY (set as an env var or in .env)")

    anki_request("createDeck", deck=args.deck)

    existing = anki_request("findNotes", query=f'deck:"{args.deck}" Hindi:"{args.hindi}"')
    if existing:
        print(f"Skipped: '{args.hindi}' already exists in {args.deck} (note {existing[0]})")
        return

    os.makedirs(TMP_DIR, exist_ok=True)
    search_query = generate_image_search_query(args.hindi, args.english, anthropic_key)
    print(f"  (image search query: '{search_query}')")
    image_urls = search_images(search_query, serp_key, num=IMAGE_CANDIDATE_POOL)

    candidate_paths = []
    for i, url in enumerate(image_urls):
        fname = f"hindi_cand_{i}_{abs(hash(args.hindi))}.jpg"
        local_path = os.path.join(TMP_DIR, fname)
        try:
            download_file(url, local_path)
            candidate_paths.append(local_path)
        except Exception as e:
            print(f"  (skipped a candidate image: {e})")

    chosen_paths = (
        select_best_images(args.hindi, args.english, candidate_paths, anthropic_key, keep=args.images)
        if candidate_paths
        else []
    )

    img_tags = []
    for path in chosen_paths:
        fname = os.path.basename(path)
        try:
            with open(path, "rb") as f:
                b64 = base64.b64encode(f.read()).decode()
            anki_request("storeMediaFile", filename=fname, data=b64)
            img_tags.append(f'<img src="{fname}">')
        except Exception as e:
            print(f"  (skipped an image: {e})")

    sound_tag = ""
    try:
        mp3_url = find_forvo_mp3_url(args.hindi, forvo_key)
        if mp3_url:
            fname = f"hindi_sound_{abs(hash(args.hindi))}.mp3"
            local_path = os.path.join(TMP_DIR, fname)
            download_file(mp3_url, local_path)
            with open(local_path, "rb") as f:
                b64 = base64.b64encode(f.read()).decode()
            anki_request("storeMediaFile", filename=fname, data=b64)
            sound_tag = f"[sound:{fname}]"
        else:
            print(f"  (no Forvo pronunciation found for '{args.hindi}', leaving Sound blank)")
    except Exception as e:
        print(f"  (skipped audio: {e})")

    pronunciation = args.pronunciation or get_pronunciation(args.hindi, anthropic_key)
    example = generate_example_sentence(args.hindi, args.english, anthropic_key)

    fields = {
        "Hindi": args.hindi,
        "English": args.english,
        "Gender": args.gender,
        "Pronunciation": pronunciation,
        "Sound": sound_tag,
        "image": "".join(img_tags),
        "Example": example,
    }

    note = {
        "deckName": args.deck,
        "modelName": MODEL,
        "fields": fields,
        "options": {"allowDuplicate": True},
        "tags": ["auto-generated"],
    }
    note_id = anki_request("addNote", note=note)
    print(
        f"Added note {note_id} for '{args.hindi}' ({pronunciation}) "
        f"with {len(img_tags)} image(s), sound={'yes' if sound_tag else 'no'}, "
        f"example={'yes' if example else 'no'}"
    )


if __name__ == "__main__":
    main()
